clone:
  depth: 50
  recursive: true
build:
  image: nice/ld-docker-build
  commands:
    - ./build.sh
publish:
  docker:
    repo: nice/ontologies
    username: $$DOCKERHUB_USER
    password: $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL
    file: Dockerfile
    insecure: false
    tag:
      - latest
      - $$COMMIT

