build:
  image: nice/ld-docker-build
publish:
  docker:
    repo: nice/ontologies
    username: $$DOCKERHUB_USER
    password: $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL
    file: Dockerfile
    insecure: false
    tag:
      - latest
      - $$COMMIT
